{% set name = "orjsonl" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orjsonl-{{ version }}.tar.gz
  sha256: 5097e7d099a0700a173dbabd90285245442b7940e52386b1470ca1678125e763

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - orjson >=3.7.7
    - xopen >=1.7.0

test:
  imports:
    - orjsonl
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/umarbutler/orjsonl
  dev_url: https://github.com/umarbutler/orjsonl
  summary: A lightweight, high-performance Python library for parsing jsonl files.
  description: |
    orjsonl is a lightweight, high-performance Python library for parsing jsonl files.
    It supports a wide variety of compression formats, including gzip, bzip2, xz and Zstandard.
    It is powered by orjson, the fastest and most accurate json serializer for Python.

extra:
  recipe-maintainers:
    - corneliusroemer
